application:
  domain: localhost:8080
  host: 0.0.0.0
  ishttps: false
  mode: dev
  name: fiber-web
  port: "8080"
  readtimeout: 1
  writertimeout: 2
db:
  collection: todolist
  database: demo
  host: localhost
  port: 27017
settings:
  application:
    port: "8888"
  log:
    compress: 1
    consolestdout: 1
    filestdout: 0
    level: debug
    localtime: 1
    maxage: 30
    maxbackups: 300
    maxsize: 10240
    path: ./logs/ferry.log
